// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvrIJoxKpu0jmgnY77nsB_YqAVJHrJzi8',
    appId: '1:691170170434:web:20bffa9c8af26bd057ffdb',
    messagingSenderId: '691170170434',
    projectId: 'devpulse-af21b',
    authDomain: 'devpulse-af21b.firebaseapp.com',
    storageBucket: 'devpulse-af21b.firebasestorage.app',
    measurementId: 'G-KQGG70NBR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY5ye5F_kMmbk26SC23Sh44drZDXOju8A',
    appId: '1:691170170434:android:7c553f8096f1e85f57ffdb',
    messagingSenderId: '691170170434',
    projectId: 'devpulse-af21b',
    storageBucket: 'devpulse-af21b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVVY5SsJDHr4YKhsgd2PIvkTlp5dLNN9I',
    appId: '1:691170170434:ios:a19bb6de92e92e1c57ffdb',
    messagingSenderId: '691170170434',
    projectId: 'devpulse-af21b',
    storageBucket: 'devpulse-af21b.firebasestorage.app',
    iosClientId: '691170170434-ae8vikaqfjhafs1qlkh82ngs5n6i1gmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.devpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVVY5SsJDHr4YKhsgd2PIvkTlp5dLNN9I',
    appId: '1:691170170434:ios:a19bb6de92e92e1c57ffdb',
    messagingSenderId: '691170170434',
    projectId: 'devpulse-af21b',
    storageBucket: 'devpulse-af21b.firebasestorage.app',
    iosClientId: '691170170434-ae8vikaqfjhafs1qlkh82ngs5n6i1gmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.devpulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvrIJoxKpu0jmgnY77nsB_YqAVJHrJzi8',
    appId: '1:691170170434:web:cf47189f3424522657ffdb',
    messagingSenderId: '691170170434',
    projectId: 'devpulse-af21b',
    authDomain: 'devpulse-af21b.firebaseapp.com',
    storageBucket: 'devpulse-af21b.firebasestorage.app',
    measurementId: 'G-2SEJBBXPXK',
  );
}
